name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'

      - name: Set up golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

      - name: Install dependencies
        run: go mod tidy

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.out
          flags: unittests
          fail_ci_if_error: true

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test
