name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: latest

      - name: Install dependencies
        run: go mod tidy

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test
